"""온톨로지 정본 (Phase 1 산출물).

- BUCKETS         : case_card 플래그 67개 → 4군(symptom/context/change/intervention)
- SYMPTOM_KO/SYN  : 증상 버킷 26개 canonical 플래그의 한글명·동의어(Ada 흡수)
- DISEASES        : Ada 26 질병 (slug → 영문/한글/KCD/분류/요약)
- DISEASE_SYMPTOMS: 질병 slug → canonical 증상 플래그 리스트 (Ada 증상 매핑 결과)
- UNMAPPED        : 어떤 플래그에도 안 붙은 Ada 증상 (보고 대상)

심리상담 플래그는 우울/불안/중독 중심 → 그 3계열은 풍부히 매핑되나
정신병/조증/신경발달/치매/신경학/신체 특이증상은 대거 미매핑(UNMAPPED).
"""

# ── 1. 버킷맵: 67 플래그 → 4군 ──────────────────────────────────
BUCKETS = {
    # 증상 (symptom) — 환자가 겪는 임상 증상/징후. 이것만 symptom 마스터로 적재.
    "depressive_mood": "symptom",
    "worthlessness": "symptom",
    "guilt": "symptom",
    "anhedonia": "symptom",
    "fatigue": "symptom",
    "sleep_disturbance": "symptom",
    "weight_appetite": "symptom",
    "impaired_cognition": "symptom",
    "psychomotor_changes": "symptom",
    "suicidal": "symptom",
    "anxiety_mood": "symptom",
    "irritability": "symptom",
    "physical_symptoms": "symptom",
    "concentration": "symptom",
    "derealization": "symptom",
    "avoidance": "symptom",
    "perceived_loss_of_control": "symptom",
    "craving": "symptom",
    "loss_of_control": "symptom",
    "tolerance": "symptom",
    "withdrawal": "symptom",
    "salience": "symptom",
    "reward_sensitivity": "symptom",
    "negative_consequences": "symptom",
    "negative_self-image": "symptom",
    "irrational_beliefs": "symptom",
    # 맥락/위험 (context) — 배경·위험요인. 증상 아님.
    "stressful_event": "context",
    "family_history": "context",
    "history_of_mental_illness": "context",
    "underlying_physical_condition": "context",
    "social_support": "context",
    "social_resources": "context",
    "lifestyle": "context",
    "social_norms": "context",
    "social_problems": "context",
    "daily_functioning": "context",
    "opportunity": "context",
    "resource_investment": "context",
    "coping": "context",
    "belief": "context",
    "unrealistic_recovery_expectations": "context",
    "external_attribution": "context",
    "lying": "context",
    "trauma_experience": "context",
    # 변화 (change) — 치료적 변화·자기조절 지표.
    "cognitive_change": "change",
    "emotional_change": "change",
    "behavioral_change": "change",
    "acceptance_change": "change",
    "motivation_for_change": "change",
    "self_management": "change",
    "self_control": "change",
    "anxiety_control": "change",
    "accepting_attitude": "change",
    "emotional_regulation": "change",
    "emotional_requlation": "change",
    # 개입 (intervention) — 상담사 기법.
    "sympathy_support": "intervention",
    "clarification_reflection": "intervention",
    "structuring": "intervention",
    "cognitive_restructuring": "intervention",
    "process_feedback": "intervention",
    "information_provision": "intervention",
    "enhancement_of_motivation": "intervention",
    "training_of_coping_skills": "intervention",
    "task_assignment": "intervention",
    "goal_setting": "intervention",
    "emotional_regulation_education_training": "intervention",
    "behavioral_intervention": "intervention",
}

# ── 2. 증상 마스터 (26) : canonical → 한글명 ────────────────────
SYMPTOM_KO = {
    "depressive_mood": "우울 기분",
    "worthlessness": "무가치감",
    "guilt": "죄책감",
    "anhedonia": "흥미상실/무쾌감",
    "fatigue": "피로/무기력",
    "sleep_disturbance": "수면장애",
    "weight_appetite": "체중·식욕 변화",
    "impaired_cognition": "인지저하(기억·판단)",
    "psychomotor_changes": "정신운동 변화(초조·지체)",
    "suicidal": "자살 사고",
    "anxiety_mood": "불안 기분",
    "irritability": "과민/짜증",
    "physical_symptoms": "신체증상(자율신경)",
    "concentration": "집중곤란",
    "derealization": "비현실감/이인감",
    "avoidance": "회피/위축",
    "perceived_loss_of_control": "통제상실감",
    "craving": "갈망",
    "loss_of_control": "통제력 상실",
    "tolerance": "내성",
    "withdrawal": "금단",
    "salience": "현저성/집착",
    "reward_sensitivity": "보상 민감성",
    "negative_consequences": "부정적 결과에도 지속",
    "negative_self-image": "부정적 자기상",
    "irrational_beliefs": "비합리적 신념/파국적 사고",
}

# 동의어 (Ada/표현 흡수). 임베딩·정규화 보조.
SYNONYMS = {
    "depressive_mood": ["저기분", "슬픔", "눈물", "low mood", "sadness"],
    "worthlessness": ["무망감", "절망감", "hopelessness", "worthless"],
    "guilt": ["죄의식", "수치심", "guilt", "shame"],
    "anhedonia": ["흥미상실", "무쾌감", "정서적 소진", "loss of interest", "anhedonia"],
    "fatigue": ["무기력", "기운없음", "에너지 고갈", "lethargy", "low energy"],
    "sleep_disturbance": ["불면", "과다수면", "수면문제", "insomnia", "hypersomnia"],
    "weight_appetite": ["식욕변화", "체중변화", "음식갈망", "appetite change", "weight change"],
    "impaired_cognition": [
        "기억력 저하",
        "건망",
        "판단력 저하",
        "혼란",
        "memory loss",
        "confusion",
    ],
    "psychomotor_changes": ["초조", "안절부절", "정신운동 지체", "agitation", "restlessness"],
    "suicidal": ["자살 사고", "죽음에 대한 생각", "자살 시도", "suicidal ideation"],
    "anxiety_mood": ["불안", "걱정", "긴장", "공황", "anxiety", "worry", "panic"],
    "irritability": ["짜증", "분노", "공격성", "irritability", "anger"],
    "physical_symptoms": [
        "두근거림",
        "발한",
        "떨림",
        "호흡곤란",
        "흉통",
        "어지럼",
        "palpitations",
        "sweating",
    ],
    "concentration": ["주의 산만", "집중 저하", "difficulty concentrating", "distractible"],
    "derealization": ["비현실감", "이인감", "해리", "derealization", "depersonalization"],
    "avoidance": ["회피", "사회적 위축", "고립", "avoidance", "withdrawal"],
    "perceived_loss_of_control": ["통제 상실 공포", "압도감", "loss of control"],
    "craving": ["갈망", "음주 갈망", "craving"],
    "loss_of_control": ["조절 실패", "통제력 상실", "loss of control"],
    "tolerance": ["내성", "tolerance"],
    "withdrawal": ["금단", "금단증상", "withdrawal"],
    "salience": ["집착", "현저성", "preoccupation", "salience"],
    "reward_sensitivity": ["보상 민감성", "충동성", "reward sensitivity"],
    "negative_consequences": ["부정적 결과 지속", "negative consequences"],
    "negative_self-image": ["낮은 자존감", "부정적 자기상", "low self-esteem"],
    "irrational_beliefs": [
        "파국적 사고",
        "비합리적 신념",
        "강박사고",
        "catastrophic thinking",
        "obsessions",
    ],
}

# ── 3. 질병 마스터 (Ada 26) : slug → (영문, 한글, KCD, 분류, 요약) ─
DISEASES = {
    "depressive-episode": (
        "Depressive Episode",
        "우울 삽화(우울증)",
        "F32",
        "mood",
        "2주 이상 지속되는 저조한 기분과 흥미 상실로 일상 기능이 저하되는 기분장애.",
    ),
    "depression-in-childhood-or-adolescence": (
        "Depression in Childhood or Adolescence",
        "소아·청소년 우울증",
        "F32",
        "mood",
        "아동·청소년기에 나타나는 우울증으로, 연령에 따라 표현 양상이 다름.",
    ),
    "bipolar-affective-disorder": (
        "Bipolar Affective Disorder",
        "양극성 정동장애(조울증)",
        "F31",
        "mood",
        "조증(또는 경조증)과 우울 삽화가 교대로 나타나는 기분장애.",
    ),
    "cyclothymic-disorder": (
        "Cyclothymic Disorder",
        "순환성 장애",
        "F34.0",
        "mood",
        "경조증과 경한 우울이 만성적으로 반복되는 경한 양극성 장애.",
    ),
    "seasonal-affective-disorder": (
        "Seasonal Affective Disorder",
        "계절성 정동장애",
        "F33",
        "mood",
        "특정 계절(주로 겨울)에 반복적으로 발생하는 우울증.",
    ),
    "premenstrual-dysphoric-disorder-pmdd": (
        "Premenstrual Dysphoric Disorder (PMDD)",
        "월경전 불쾌장애",
        "N94.3",
        "mood",
        "월경 전 주기에 심한 정서·신체 증상이 나타나는 중증 월경전증후군.",
    ),
    "generalized-anxiety-disorder": (
        "Generalized Anxiety Disorder",
        "범불안장애",
        "F41.1",
        "anxiety",
        "다양한 일에 대한 과도하고 통제되지 않는 만성 불안.",
    ),
    "acute-panic-attack": (
        "Acute Panic Attack",
        "급성 공황발작",
        "F41.0",
        "anxiety",
        "갑작스러운 극심한 공포와 신체 증상이 수 분간 몰아치는 발작.",
    ),
    "signs-of-panic-attack": (
        "Signs of Panic Attack",
        "공황발작 징후",
        "F41.0",
        "anxiety",
        "공황발작을 시사하는 신체·심리 징후.",
    ),
    "obsessive-compulsive-disorder": (
        "Obsessive Compulsive Disorder",
        "강박장애",
        "F42",
        "ocd",
        "침습적 강박사고와 이를 줄이려는 반복 강박행동이 특징인 장애.",
    ),
    "post-traumatic-stress-disorder": (
        "Post Traumatic Stress Disorder",
        "외상후 스트레스장애(PTSD)",
        "F43.1",
        "trauma",
        "외상 경험 후 재경험·회피·과각성이 지속되는 외상후 장애.",
    ),
    "acute-stress-disorder": (
        "Acute Stress Disorder",
        "급성 스트레스장애",
        "F43.0",
        "trauma",
        "외상 직후(약 1개월 이내) 나타나는 단기 스트레스 반응.",
    ),
    "adjustment-disorder": (
        "Adjustment Disorder",
        "적응장애",
        "F43.2",
        "trauma",
        "특정 스트레스 사건에 대한 부적응적 정서·행동 반응.",
    ),
    "burnout": (
        "Burnout",
        "번아웃(소진 증후군)",
        "Z73.0",
        "trauma",
        "만성 직무 스트레스로 인한 정서적 소진·냉소·효능감 저하 상태.",
    ),
    "schizophrenia": (
        "Schizophrenia",
        "조현병",
        "F20",
        "psychotic",
        "망상·환각 등 현실검증력이 손상되는 만성 정신병적 장애.",
    ),
    "borderline-personality-disorder": (
        "Borderline Personality Disorder",
        "경계성 인격장애",
        "F60.3",
        "personality",
        "정서·대인관계·자기상이 불안정하고 충동적인 인격장애.",
    ),
    "autism": (
        "Autism",
        "자폐 스펙트럼 장애",
        "F84.0",
        "neurodevelopmental",
        "사회적 의사소통 결함과 제한적·반복적 행동이 특징인 신경발달장애.",
    ),
    "asperger-syndrome": (
        "Asperger Syndrome",
        "아스퍼거 증후군",
        "F84.5",
        "neurodevelopmental",
        "지적·언어 지연 없이 사회성·관심범위 제한이 나타나는 자폐 스펙트럼의 한 형태.",
    ),
    "attention-deficit-hyperactivity-disorder": (
        "ADHD",
        "주의력결핍 과잉행동장애(ADHD)",
        "F90",
        "neurodevelopmental",
        "부주의·과잉행동·충동성이 지속되는 신경발달장애.",
    ),
    "fetal-alcohol-spectrum-disorders": (
        "Fetal Alcohol Spectrum Disorders",
        "태아 알코올 스펙트럼 장애",
        "Q86.0",
        "neurodevelopmental",
        "임신 중 음주로 태아에 생기는 신체·인지·행동 손상.",
    ),
    "alcohol-intoxication": (
        "Alcohol Intoxication",
        "알코올 중독(급성)",
        "F10.0",
        "substance",
        "음주로 인한 급성 중추신경계 기능 저하(취한 상태).",
    ),
    "alcohol-withdrawal": (
        "Alcohol Withdrawal",
        "알코올 금단",
        "F10.3",
        "substance",
        "알코올 의존자가 음주를 중단·감량할 때 나타나는 금단 증상군.",
    ),
    "conversion-disorder": (
        "Conversion Disorder",
        "전환장애",
        "F44",
        "somatic",
        "신경학적 원인 없이 운동·감각 기능 이상이 나타나는 장애.",
    ),
    "alzheimers-disease": (
        "Alzheimer's Disease",
        "알츠하이머병",
        "G30",
        "neurocognitive",
        "기억력부터 점진적으로 악화되는 가장 흔한 퇴행성 치매.",
    ),
    "dementia-with-lewy-bodies": (
        "Dementia With Lewy Bodies",
        "루이소체 치매",
        "G31.8",
        "neurocognitive",
        "환시·인지변동·파킨슨 운동증상이 특징인 치매.",
    ),
    "hiv-dementia": (
        "HIV and Dementia",
        "HIV 치매",
        "F02.4",
        "neurocognitive",
        "HIV 감염이 뇌를 침범해 생기는 인지기능 저하.",
    ),
}

# ── 4. 질병 → 증상 매핑 (Ada 증상 → canonical 플래그) ───────────
DISEASE_SYMPTOMS = {
    "depressive-episode": [
        "depressive_mood",
        "anhedonia",
        "worthlessness",
        "guilt",
        "fatigue",
        "impaired_cognition",
        "sleep_disturbance",
        "weight_appetite",
        "psychomotor_changes",
        "irritability",
        "physical_symptoms",
        "suicidal",
    ],
    "depression-in-childhood-or-adolescence": [
        "depressive_mood",
        "anhedonia",
        "fatigue",
        "irritability",
        "concentration",
        "impaired_cognition",
        "sleep_disturbance",
        "weight_appetite",
        "physical_symptoms",
        "suicidal",
    ],
    "bipolar-affective-disorder": ["depressive_mood", "worthlessness", "suicidal"],
    "cyclothymic-disorder": [
        "depressive_mood",
        "anhedonia",
        "worthlessness",
        "guilt",
        "fatigue",
        "sleep_disturbance",
        "weight_appetite",
        "concentration",
        "impaired_cognition",
        "psychomotor_changes",
        "irritability",
        "suicidal",
    ],
    "seasonal-affective-disorder": [
        "depressive_mood",
        "anhedonia",
        "worthlessness",
        "guilt",
        "fatigue",
        "sleep_disturbance",
        "weight_appetite",
        "concentration",
        "psychomotor_changes",
        "irritability",
        "anxiety_mood",
        "avoidance",
        "suicidal",
    ],
    "premenstrual-dysphoric-disorder-pmdd": [
        "depressive_mood",
        "anhedonia",
        "worthlessness",
        "irritability",
        "anxiety_mood",
        "negative_self-image",
        "perceived_loss_of_control",
        "concentration",
        "sleep_disturbance",
        "weight_appetite",
        "fatigue",
        "physical_symptoms",
    ],
    "generalized-anxiety-disorder": [
        "anxiety_mood",
        "perceived_loss_of_control",
        "physical_symptoms",
        "psychomotor_changes",
        "irritability",
        "sleep_disturbance",
        "concentration",
    ],
    "acute-panic-attack": [
        "anxiety_mood",
        "physical_symptoms",
        "derealization",
        "perceived_loss_of_control",
    ],
    "signs-of-panic-attack": [
        "anxiety_mood",
        "physical_symptoms",
        "derealization",
        "perceived_loss_of_control",
        "avoidance",
        "irrational_beliefs",
    ],
    "obsessive-compulsive-disorder": ["anxiety_mood", "irrational_beliefs"],
    "post-traumatic-stress-disorder": [
        "avoidance",
        "concentration",
        "sleep_disturbance",
        "irritability",
        "guilt",
        "anhedonia",
        "derealization",
        "negative_self-image",
        "physical_symptoms",
    ],
    "acute-stress-disorder": [
        "anxiety_mood",
        "depressive_mood",
        "physical_symptoms",
        "concentration",
        "sleep_disturbance",
        "irritability",
        "avoidance",
        "derealization",
    ],
    "adjustment-disorder": ["depressive_mood", "anxiety_mood"],
    "burnout": ["fatigue", "anhedonia", "worthlessness", "negative_self-image"],
    "schizophrenia": ["anhedonia", "avoidance", "impaired_cognition", "concentration"],
    "borderline-personality-disorder": ["irritability", "perceived_loss_of_control"],
    "autism": [],
    "asperger-syndrome": [],
    "attention-deficit-hyperactivity-disorder": [
        "concentration",
        "impaired_cognition",
        "psychomotor_changes",
    ],
    "fetal-alcohol-spectrum-disorders": ["impaired_cognition", "concentration"],
    "alcohol-intoxication": ["physical_symptoms"],
    "alcohol-withdrawal": [
        "anxiety_mood",
        "psychomotor_changes",
        "irritability",
        "sleep_disturbance",
        "physical_symptoms",
        "craving",
        "weight_appetite",
    ],
    "conversion-disorder": ["impaired_cognition"],
    "alzheimers-disease": [
        "impaired_cognition",
        "concentration",
        "psychomotor_changes",
        "irritability",
        "weight_appetite",
        "sleep_disturbance",
    ],
    "dementia-with-lewy-bodies": ["sleep_disturbance", "depressive_mood"],
    "hiv-dementia": ["impaired_cognition", "concentration", "psychomotor_changes", "anhedonia"],
}

# ── 5. 미매핑 보고 : 어떤 플래그에도 안 붙은 Ada 증상 ───────────
UNMAPPED = {
    "depression-in-childhood-or-adolescence": ["자해행동"],
    "bipolar-affective-disorder": [
        "조증(고양된 기분·과활동·과대성)",
        "경조증",
        "정신병적 증상(환각·망상)",
        "기분 변동",
    ],
    "cyclothymic-disorder": [
        "충동·위험행동",
        "고양된 기분/과도한 낙관/자신감",
        "탈억제",
        "사고질주·다변",
        "성욕 증가",
    ],
    "premenstrual-dysphoric-disorder-pmdd": ["유방 압통", "복부팽만", "설사", "손발 부종"],
    "acute-panic-attack": ["죽음에 대한 공포"],
    "signs-of-panic-attack": ["무력감"],
    "obsessive-compulsive-disorder": ["강박행동(반복 청결·확인·정렬·재확인)"],
    "post-traumatic-stress-disorder": ["재경험/플래시백/침습기억", "무감각(numbing)"],
    "acute-stress-disorder": ["침습/플래시백"],
    "adjustment-disorder": ["사회·직업 기능 저하"],
    "burnout": ["냉소·탈인격화", "직무 관련 부정 감정"],
    "schizophrenia": ["환각", "망상", "와해된 사고/언어/행동", "정서 둔마", "무의욕"],
    "borderline-personality-disorder": [
        "정서 불안정",
        "충동성",
        "자해",
        "만성 공허감",
        "대인관계 불안정",
    ],
    "autism": [
        "사회적 의사소통 결함",
        "제한적·반복적 행동",
        "감각 이상",
        "눈맞춤 결여",
        "루틴 집착",
    ],
    "asperger-syndrome": ["사회성 결함", "제한적 관심", "감각 과민", "운동 서투름"],
    "attention-deficit-hyperactivity-disorder": ["과잉행동", "충동성"],
    "fetal-alcohol-spectrum-disorders": ["안면 기형", "저성장", "소두증", "발달 지연", "지적장애"],
    "alcohol-intoxication": ["도취/탈억제", "운동실조", "발음 어눌", "혼수", "호흡부전"],
    "alcohol-withdrawal": ["환각", "경련", "진전섬망"],
    "conversion-disorder": [
        "실명",
        "마비/위약",
        "발작",
        "감각 상실",
        "발성불능",
        "운동틱",
        "가성임신",
    ],
    "alzheimers-disease": ["환각·망상", "배회", "시공간 장애", "요실금", "발작", "실행기능 상실"],
    "dementia-with-lewy-bodies": [
        "환시",
        "파킨슨증(떨림·경직)",
        "인지 변동",
        "자율신경 이상",
        "실금",
    ],
    "hiv-dementia": ["언어 느림", "무감정(apathy)"],
}

# ── 6. 증상 보강 (Tier 1+2, source='ada') : Ada 미매핑 → 신규 canonical 증상 ──
EXT_SYMPTOMS = {
    # Tier 1 — 안전·감별 필수
    "hallucination": ("환각", ["환청", "환시", "hallucination"]),
    "delusion": ("망상", ["피해망상", "과대망상", "delusion", "paranoia"]),
    "disorganized_thought": (
        "와해된 사고·언어",
        ["사고 와해", "와해된 언어", "disorganized speech"],
    ),
    "elevated_mood": ("고양된 기분(조증)", ["들뜬 기분", "과대성", "다행감", "mania", "euphoria"]),
    "self_harm": ("자해", ["자해행동", "자기손상", "self-harm", "self-injury"]),
    "flashback": ("재경험/플래시백", ["침습 기억", "악몽", "re-experiencing", "flashback"]),
    "emotional_numbing": (
        "정서적 무감각/둔마",
        ["무감각", "정서 둔마", "무감정", "numbing", "blunted affect"],
    ),
    # Tier 2 — 감별 확장
    "impulsivity": ("충동성", ["충동조절 곤란", "위험행동", "탈억제", "impulsivity"]),
    "compulsions": (
        "강박행동",
        ["반복 확인", "손씻기", "정렬", "의식행동", "compulsion", "ritual"],
    ),
    "hyperactivity": ("과잉행동", ["과활동", "가만히 못 있음", "hyperactivity"]),
    "social_communication_deficit": (
        "사회적 의사소통 결함",
        ["눈맞춤 결여", "사회성 결핍", "social deficit"],
    ),
    "restricted_repetitive_behavior": (
        "제한적·반복적 행동",
        ["상동행동", "루틴 집착", "좁은 관심", "repetitive behavior"],
    ),
    "sensory_abnormality": ("감각 이상/과민", ["감각 과민", "감각 둔감", "sensory sensitivity"]),
    "interpersonal_instability": (
        "대인관계 불안정",
        ["관계 불안정", "버림받음 공포", "unstable relationships"],
    ),
}
ADA_SOURCE = set(EXT_SYMPTOMS)
for _f, (_ko, _syn) in EXT_SYMPTOMS.items():
    BUCKETS[_f] = "symptom"
    SYMPTOM_KO[_f] = _ko
    SYNONYMS[_f] = _syn

# 보강 엣지 (미매핑 Ada 증상 → 신규 플래그)
EXT_EDGES = {
    "depression-in-childhood-or-adolescence": ["self_harm"],
    "bipolar-affective-disorder": ["elevated_mood", "hallucination", "delusion"],
    "cyclothymic-disorder": ["elevated_mood", "impulsivity"],
    "obsessive-compulsive-disorder": ["compulsions"],
    "post-traumatic-stress-disorder": ["flashback", "emotional_numbing"],
    "acute-stress-disorder": ["flashback"],
    "burnout": ["emotional_numbing"],
    "schizophrenia": ["hallucination", "delusion", "disorganized_thought", "emotional_numbing"],
    "borderline-personality-disorder": [
        "impulsivity",
        "self_harm",
        "interpersonal_instability",
        "emotional_numbing",
    ],
    "autism": [
        "social_communication_deficit",
        "restricted_repetitive_behavior",
        "sensory_abnormality",
    ],
    "asperger-syndrome": [
        "social_communication_deficit",
        "restricted_repetitive_behavior",
        "sensory_abnormality",
    ],
    "attention-deficit-hyperactivity-disorder": ["hyperactivity", "impulsivity"],
    "alcohol-intoxication": ["impulsivity"],
    "alcohol-withdrawal": ["hallucination"],
    "alzheimers-disease": ["hallucination", "delusion"],
    "dementia-with-lewy-bodies": ["hallucination"],
    "hiv-dementia": ["emotional_numbing"],
}
for _slug, _flags in EXT_EDGES.items():
    DISEASE_SYMPTOMS[_slug] = DISEASE_SYMPTOMS.get(_slug, []) + _flags

# 보강 후 남는 미매핑 = Tier 3 (신체/신경/발달 특이증상 → Ada 텍스트에 위임)
UNMAPPED = {
    "premenstrual-dysphoric-disorder-pmdd": ["유방 압통", "복부팽만", "설사", "손발 부종"],
    "acute-panic-attack": ["죽음에 대한 공포"],
    "signs-of-panic-attack": ["무력감"],
    "adjustment-disorder": ["사회·직업 기능 저하"],
    "fetal-alcohol-spectrum-disorders": ["안면 기형", "저성장", "소두증", "발달 지연", "지적장애"],
    "alcohol-intoxication": ["운동실조", "발음 어눌", "혼수", "호흡부전"],
    "alcohol-withdrawal": ["경련", "진전섬망"],
    "conversion-disorder": [
        "실명",
        "마비/위약",
        "발작",
        "감각 상실",
        "발성불능",
        "운동틱",
        "가성임신",
    ],
    "alzheimers-disease": ["배회", "시공간 장애", "요실금", "발작", "실행기능 상실"],
    "dementia-with-lewy-bodies": ["파킨슨증(떨림·경직)", "인지 변동", "자율신경 이상", "실금"],
    "hiv-dementia": ["언어 느림"],
}

SYMPTOMS = [f for f, b in BUCKETS.items() if b == "symptom"]  # 26 + 14 = 40

if __name__ == "__main__":
    from collections import Counter

    print("버킷 분포:", dict(Counter(BUCKETS.values())))
    print("증상 마스터:", len(SYMPTOMS))
    print("질병:", len(DISEASES))
    edges = sum(len(v) for v in DISEASE_SYMPTOMS.values())
    print("disease_symptom 엣지:", edges)
    unmapped = sum(len(v) for v in UNMAPPED.values())
    print("미매핑 Ada 증상:", unmapped)
    nomap = [s for s, v in DISEASE_SYMPTOMS.items() if not v]
    print("증상 0개 질병:", nomap)
